
Sun, 26 Dec 2010 19:58:19 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4.1-linux/bin/pypy knucleotide.pypy-2.pypy 0 < knucleotide-input250000.txt

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "knucleotide.pypy-2.pypy", line 11, in <module>
    from multiprocessing import Process, Pool, cpu_count
ImportError: No module named multiprocessing
