
Wed, 13 Oct 2010 14:34:22 GMT

COMMAND LINE:
/usr/local/src/pypy-1.3/bin/pypy knucleotide.pypy-5.pypy 0 < knucleotide-input250000.txt

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "knucleotide.pypy-5.pypy", line 12, in <module>
    from multiprocessing import Process, Pool, cpu_count
ImportError: No module named multiprocessing
