
Sun, 26 Dec 2010 20:26:59 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4.1-linux/bin/pypy nbody.pypy-4.pypy 500000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 53, in run_toplevel
  File "nbody.pypy-4.pypy", line 51, in <module>
    PAIRS = list(itertools.combinations(SYSTEM, 2))
AttributeError: 'module' object has no attribute 'combinations'
