
Fri, 26 Nov 2010 22:21:01 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4/bin/pypy pidigits.pypy-2.pypy 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "pidigits.pypy-2.pypy", line 7, in <module>
    from gmpy import mpz
ImportError: No module named gmpy
