
Thu, 02 Dec 2010 00:08:25 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4/bin/pypy regexdna.pypy 0 < regexdna-input50000.txt

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "regexdna.pypy", line 9, in <module>
    from multiprocessing import Pool
ImportError: No module named multiprocessing
