
Mon, 20 Sep 2010 08:03:20 GMT

COMMAND LINE:
/usr/local/src/pypy-1.3/bin/pypy spectralnorm.pypy-5.pypy 500

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "spectralnorm.pypy-5.pypy", line 9, in <module>
    from multiprocessing import Pool
ImportError: No module named multiprocessing
