
Fri, 03 Dec 2010 23:24:41 GMT

COMMAND LINE:
/usr/local/src/pypy-1.4/bin/pypy spectralnorm.pypy-7.pypy 500

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "app_main.py", line 33, in run_toplevel
  File "spectralnorm.pypy-7.pypy", line 10, in <module>
    from multiprocessing import Pool, cpu_count
ImportError: No module named multiprocessing
