
Tue, 21 Apr 2009 02:22:25 GMT

MAKE:
mv meteor.python3-3.python3 meteor.python3-3.py
/usr/local/src/Python-3.1a2/bin/python3.1 -OO -c "from py_compile import compile; compile('meteor.python3-3.py')"
0.06s to complete and log all make actions

COMMAND LINE:
/usr/local/src/Python-3.1a2/bin/python3.1 meteor.python3-3.pyo 2098

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "meteor.python3-3.py", line 98, in <module>
    board, cti, pieces = get_puzzle()
  File "meteor.python3-3.py", line 83, in get_puzzle
    pieces = [[convert(pp) for pp in p] for p in perms]
  File "meteor.python3-3.py", line 83, in <listcomp>
    pieces = [[convert(pp) for pp in p] for p in perms]
  File "meteor.python3-3.py", line 82, in <genexpr>
    perms = (permute(p, idos[3]) for p in idos)    # restrict piece 4
  File "meteor.python3-3.py", line 31, in permute
    ps = ps[0:dir_no/2]
TypeError: slice indices must be integers or None or have an __index__ method
