
Thu, 11 Jun 2009 19:51:11 GMT

MAKE:
mv pidigits.python3-3.python3 pidigits.python3-3.py
/usr/local/src/Python-3.1rc1/bin/python3.1 -OO -c "from py_compile import compile; compile('pidigits.python3-3.py')"
0.08s to complete and log all make actions

COMMAND LINE:
/usr/local/src/Python-3.1rc1/bin/python3.1 pidigits.python3-3.pyo 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python3-3.py", line 11, in <module>
    import gmpy
ImportError: No module named gmpy
